// packages/vue/src/BlossomCarousel.vue
<template>
  <component :is="as" ref="root" blossom-carousel="true">
    <slot />
  </component>
</template>

<script setup>
import { onMounted, onBeforeUnmount, shallowRef } from "vue";

const props = defineProps({
  as: {
    type: String,
    default: "div",
  },
  repeat: {
    type: Boolean,
    default: false,
  },
  load: {
    type: String,
    default: "conditional",
  },
});

const root = shallowRef(null);
let blossom;

defineExpose({
  el: root,
  next: () => blossom?.next(),
  prev: () => blossom?.prev(),
  currentIndex: () => blossom?.currentIndex(),
});
onMounted(async () => {
  const hasMouse = window.matchMedia(
    "(hover: hover) and (pointer: fine)"
  ).matches;

  // don't load if the user has no mouse.
  // overwritten by props.load: 'always'
  if (!hasMouse && props.load !== "always") return;

  const { Blossom } = await import("@numbered/carousel");

  blossom = Blossom(root.value, { repeat: props.repeat });
  blossom.init();
});

onBeforeUnmount(() => {
  blossom?.destroy();
});
</script>

// packages/react/src/BlossomCarousel.tsx
import { Blossom } from '@numbered/carousel'
import { type ElementType, type ReactNode, type Ref, useEffect, useImperativeHandle, useRef } from 'react'

export interface BlossomCarouselRef {
	next: () => void
	prev: () => void
	currentIndex: () => number
}

export default function BlossomCarousel({
	children,
	as: Component = 'div',
	repeat,
	load,
	onChange,
	ref,
	elementRef,
	...props
}: {
	children?: ReactNode | Array<ReactNode>
	as?: ElementType
	repeat?: boolean
	load?: 'always'
	onChange?: (event: CustomEvent<{ index: number }>) => void
	ref?: Ref<BlossomCarouselRef | null>
	elementRef?: Ref<HTMLElement | null>
	[key: string]: unknown
}) {
	const localRef = useRef<HTMLElement>(null)
	const blossomRef = useRef<ReturnType<typeof Blossom> | null>(null)

	useEffect(() => {
		if (!localRef.current) return

		const hasMouse = window.matchMedia('(hover: hover) and (pointer: fine)').matches
		if (!hasMouse && load !== 'always') return

		const blossom = Blossom(localRef.current, { repeat })
		blossomRef.current = blossom
		blossom.init()

		return () => {
			blossom.destroy()
			blossomRef.current = null
		}
	}, [repeat])

	useEffect(() => {
		if (!localRef.current || !onChange) return

		const handleChange = (e: Event) => {
			onChange(e as CustomEvent<{ index: number }>)
		}

		localRef.current.addEventListener('change', handleChange)

		return () => {
			localRef.current?.removeEventListener('change', handleChange)
		}
	}, [onChange])

	useImperativeHandle(
		ref,
		() => ({
			next: () => blossomRef.current?.next(),
			prev: () => blossomRef.current?.prev(),
			currentIndex: () => blossomRef.current?.currentIndex() ?? 0,
		}),
		[],
	)

	return (
		<Component ref={localRef} blossom-carousel='true' {...props}>
			{children}
		</Component>
	)
}
